#!/usr/bin/env python3
"""Generate category-level (city-agnostic) FAQs and upload to Supabase.
Uses pre-written high-quality FAQs instead of LLM generation.
"""

import json
import urllib.request
from pathlib import Path

# Load env
env_file = Path(__file__).parent.parent / ".env.local"
env = {}
for line in env_file.read_text().splitlines():
    if "=" in line and not line.startswith("#"):
        k, v = line.split("=", 1)
        env[k.strip()] = v.strip()

SUPABASE_URL = env["NEXT_PUBLIC_SUPABASE_URL"]
SERVICE_KEY = env["SUPABASE_SERVICE_ROLE_KEY"]

# Pre-written city-agnostic FAQs per category
CATEGORY_FAQS = {
    "hvac": [
        {"question": "How much does HVAC repair cost in Johnson County?", "answer": "Most HVAC repairs in the Johnson County area range from $150-$600, with the average service call running around $300. Major component replacements like a compressor or furnace heat exchanger can run $1,000-$3,000+. Many local companies offer free estimates and seasonal maintenance plans that include priority scheduling and discounts on repairs."},
        {"question": "Do I need a permit for HVAC work in Johnson County?", "answer": "Yes, most cities in Johnson County require a permit for new HVAC installations and sometimes for major replacements. Your HVAC contractor should pull the permit as part of their service. Make sure any contractor you hire is licensed with the Kansas State Board of Examiners and carries proper insurance."},
        {"question": "How often should I service my HVAC system?", "answer": "Twice a year is recommended: once in spring for your air conditioning system and once in fall for your heating system. Regular maintenance extends equipment life by 5-10 years, improves efficiency by up to 25%, and catches small problems before they become expensive repairs. Most Johnson County HVAC companies offer annual maintenance agreements for $150-$300."},
        {"question": "What are signs I need to replace my HVAC system?", "answer": "Key indicators include: age over 15-20 years, frequent repairs costing more than half the price of a new system, uneven heating or cooling, rising energy bills despite same usage, and strange noises or odors. Modern systems are significantly more efficient — upgrading from a 10 SEER to a 16+ SEER system can cut cooling costs by 30-40%."},
        {"question": "Should I repair or replace my furnace or AC?", "answer": "Use the $5,000 rule: multiply the age of your unit by the repair cost. If the result exceeds $5,000, replacement is usually the better investment. For example, a 12-year-old furnace with a $400 repair ($4,800) is borderline, while a $600 repair on that same unit ($7,200) tips toward replacement. Also consider that new systems come with warranties and rebates."},
        {"question": "What HVAC brands are most reliable in the Kansas City climate?", "answer": "The Kansas City metro area has hot, humid summers and cold winters, so you need a system built for both extremes. Top-performing brands locally include Trane, Carrier, Lennox, and Rheem. More important than brand is proper sizing and installation — an undersized or poorly installed system from any brand will underperform. Always get 2-3 quotes and verify the contractor does a Manual J load calculation."},
    ],
    "plumbing": [
        {"question": "How much does a plumber cost in Johnson County?", "answer": "Plumbers in Johnson County typically charge $75-$150 per hour, with a minimum service call fee of $100-$200. Common jobs: drain cleaning $150-$350, water heater replacement $800-$2,500, toilet repair $100-$300, and faucet replacement $150-$400. Emergency or after-hours calls usually carry a 50-100% premium. Always ask for a written estimate before work begins."},
        {"question": "Do I need a licensed plumber for minor repairs?", "answer": "Kansas requires a plumbing license for any work involving water supply or drain lines. While you can legally replace a faucet aerator or showerhead yourself, anything involving pipes, valves, or connections to main lines requires a licensed plumber. Unlicensed work can void your homeowner's insurance and create liability issues if it causes water damage."},
        {"question": "How do I prevent frozen pipes in Kansas winters?", "answer": "Insulate exposed pipes in unheated areas (garage, crawl space, exterior walls), disconnect garden hoses before first freeze, open cabinet doors under sinks on exterior walls during extreme cold, and let faucets drip during sub-zero nights. If a pipe freezes, never use an open flame — use a hair dryer or heat tape. Know where your main water shutoff is located."},
        {"question": "What should I do if I have a plumbing emergency?", "answer": "First, shut off the water at the main shutoff valve (know where this is before an emergency). For a burst pipe, also turn off your water heater. Then call a licensed plumber. Many Johnson County plumbers offer 24/7 emergency service. Take photos of the damage for insurance. Avoid using chemical drain cleaners on a clogged pipe — they can damage pipes and make professional repair harder."},
        {"question": "How do I choose a reliable plumber in Johnson County?", "answer": "Look for: Kansas plumbing license (verify at kansas.gov), at least 3-5 years of experience, proper insurance (general liability and workers comp), written estimates, and good reviews on Google. Get 2-3 quotes for any job over $500. Be wary of plumbers who pressure you into same-day decisions or won't provide a written guarantee."},
        {"question": "Why is my water bill suddenly higher?", "answer": "A sudden spike usually means a leak. Check: running toilets (most common — add food coloring to the tank and see if it appears in the bowl after 30 minutes), dripping faucets, water heater leaking, or a slab leak under your foundation. A running toilet can waste 200+ gallons per day. If you can't find the leak, call a plumber — slab leaks can cause serious foundation damage if left unchecked."},
    ],
    "roofing": [
        {"question": "How much does a new roof cost in Johnson County?", "answer": "Roof replacement in Johnson County runs $5,000-$15,000 for an average home, depending on materials. Asphalt shingles (most common) run $3.50-$5.50 per square foot installed. Metal roofing costs $7-$12 per square foot. Tile and slate can exceed $15 per square foot. Most roofs here are 1,500-2,500 square feet. Get at least 3 quotes, and make sure they include tear-off, disposal, and any needed plywood repair."},
        {"question": "How long does a roof last in Kansas?", "answer": "Asphalt shingle roofs in Kansas typically last 15-25 years, depending on sun exposure and storm damage. Premium architectural shingles can reach 30 years. Metal roofs last 40-70 years. Kansas weather (hail, wind, ice dams, UV) significantly shortens roof life. After any major hail storm, have your roof inspected — damage may not be visible from the ground."},
        {"question": "Should I repair or replace my roof?", "answer": "Repair if: the roof is under 10 years old, damage is limited to a small area, and shingles are still available in matching color. Replace if: the roof is over 15-20 years, you have multiple leaks, shingles are curling or missing granules, or you've had 2+ repairs in 3 years. A new roof also adds curb appeal and can increase home value by $5,000-$15,000."},
        {"question": "Does homeowner's insurance cover roof damage in Kansas?", "answer": "Most policies cover sudden damage from storms (hail, wind, fallen trees) but NOT wear and tear or aging. After a hail storm, file a claim quickly — most policies have a 1-year filing deadline. Your deductible applies ($500-$5,000 typical). Get an independent inspection before filing so you know the actual damage. Some companies now require separate roof deductibles (1-2% of home value) in Kansas."},
        {"question": "How do I choose a roofing contractor in Johnson County?", "answer": "Verify: Kansas roofing license, general liability insurance ($1M+), workers comp coverage, and at least 5 years of local experience. Get everything in writing: scope, materials, timeline, warranty, and payment terms. Never pay more than 30% upfront. Check Google reviews (look for 50+ reviews with 4.5+ stars). Be cautious of contractors who show up at your door after a storm — these are often storm chasers who won't be around for warranty claims."},
        {"question": "What time of year is best for roof replacement?", "answer": "Late spring through early fall (May-October) is ideal in Kansas. Asphalt shingles need temperatures above 40°F to seal properly. Summer is busiest and most expensive. Late fall can work but shingles may not fully seal until spring warmth. If you have an active leak, don't wait — temporary repairs (tarping) can bridge the gap until proper weather for full replacement."},
    ],
    "landscaping": [
        {"question": "How much does landscaping cost in Johnson County?", "answer": "Basic lawn maintenance runs $40-$80 per visit for a quarter-acre lot. Full landscape design and installation ranges from $3,000-$30,000+ depending on scope. Common projects: patio installation $3,000-$10,000, retaining walls $2,000-$8,000, sprinkler systems $2,500-$5,000, and tree planting $200-$600 per tree. Most companies offer free estimates for larger projects."},
        {"question": "What landscaping services are most common in Johnson County?", "answer": "The most requested services are: mowing and edging (weekly April-November), spring and fall cleanups, mulch installation ($50-$100 per yard installed), hedge trimming, aeration and overseeding, irrigation system maintenance, and landscape lighting. Many companies offer seasonal packages that combine these services at a discount."},
        {"question": "When should I aerate and overseed my lawn in Kansas?", "answer": "Early fall (late August through September) is the optimal time for cool-season grasses (tall fescue and Kentucky bluegrass), which are most common in Johnson County. Spring aeration works but fall gives new seed 6-8 weeks of ideal growing conditions before winter. Avoid summer aeration — heat stress can kill the new seedlings."},
        {"question": "How do I choose a landscaper in Johnson County?", "answer": "Look for: proper business license and insurance (general liability and workers comp), a portfolio of local projects, written contracts with specific scope and materials, and clear payment terms. Ask about their experience with Kansas clay soil and zone-appropriate plants. For design work, ask if they have a landscape architect on staff. Get 2-3 estimates for any project over $1,000."},
        {"question": "What plants grow best in Johnson County landscapes?", "answer": "Johnson County is in USDA hardiness zone 6b. Top performers include: ornamental grasses (Karl Foerster feather reed grass, miscanthus), perennials (coneflower, black-eyed Susan, sedum), shrubs (knockout roses, spirea, hydrangea), and shade trees (red maple, oak, redbud). Kansas clay soil needs amendment with compost. Avoid plants that need excellent drainage unless you're building raised beds."},
        {"question": "How much water does my lawn need in a Kansas summer?", "answer": "Lawns in Johnson County need about 1-1.5 inches of water per week during summer, either from rain or irrigation. Water deeply 2-3 times per week rather than daily shallow watering — this encourages deep root growth. The best time to water is 5-9 AM. Evening watering promotes fungus. A rain sensor on your sprinkler system can reduce water waste by 15-20%."},
    ],
    "electrician": [
        {"question": "How much does an electrician cost in Johnson County?", "answer": "Electricians in Johnson County charge $75-$150 per hour, with a typical service call fee of $100-$200. Common jobs: outlet installation $100-$250, ceiling fan installation $150-$350, panel upgrade $1,500-$3,500, whole-home rewiring $8,000-$20,000+. Emergency calls carry a premium of 1.5-2x. Always get a written estimate for any job over $500."},
        {"question": "Do I need a permit for electrical work in Johnson County?", "answer": "Yes, most electrical work requires a permit and inspection in Johnson County cities. This includes new circuits, panel upgrades, outlet additions, and wiring modifications. Simple replacements (light fixtures, switches) usually don't need permits, but new installations do. Your electrician should handle permitting. Unpermitted work can void insurance claims and cause problems when selling your home."},
        {"question": "When should I upgrade my electrical panel?", "answer": "Upgrade if: your panel is 100 amps or less and you're adding appliances, you have fuses instead of breakers, lights flicker when appliances run, breakers trip frequently, or your panel is a known hazardous brand (Federal Pacific/Zinsco). Most modern homes need 200 amps. Panel upgrades typically cost $1,500-$3,500 and require a permit and inspection."},
        {"question": "Is aluminum wiring dangerous?", "answer": "Homes built between 1965-1973 may have aluminum wiring, which is 55x more likely to cause a fire connection point than copper. Warning signs include: warm outlets, flickering lights, burning smells, and scorched outlets. If your home has aluminum wiring, have an electrician evaluate it. Solutions include complete rewiring ($8,000-$20,000) or COPALUM crimp connections ($3,000-$5,000), which are the only EPA-approved repair."},
        {"question": "How do I know if my home needs rewiring?", "answer": "Signs include: two-prong outlets (no ground), knob-and-tube wiring (visible in attic/basement), frequently tripping breakers, burning smells from outlets, flickering lights, and discolored outlets. If your home is over 40 years old and hasn't been updated, get an inspection. Most electricians offer free or low-cost inspections and will document what needs attention."},
        {"question": "Can I do my own electrical work in Kansas?", "answer": "Kansas allows homeowners to do their own electrical work on their primary residence, but you still need permits and inspections for most projects. The work must meet current NEC code. If you're not confident, don't risk it — electrical mistakes cause fires and can be fatal. For anything beyond replacing a light fixture or switch, hire a licensed electrician. The cost of a professional is far less than the risk."},
    ],
    "painting": [
        {"question": "How much does painting cost in Johnson County?", "answer": "Interior painting runs $2-$6 per square foot ($800-$3,000 per room for walls and ceiling). Exterior painting costs $2,500-$8,000 for an average home depending on size and prep work. Cabinet painting runs $3,000-$8,000. Paint quality matters — builder-grade paint lasts 3-5 years, while premium paints (Sherwin-Williams Duration, Benjamin Moore Aura) can last 10-15 years on exteriors."},
        {"question": "How do I choose a painting contractor?", "answer": "Get at least 3 detailed quotes. A professional estimate should specify: exact surfaces to be painted, prep work (scraping, sanding, caulking, priming), paint brand and grade, number of coats, and cleanup. Verify insurance and check reviews. The cheapest bid usually skips prep work — 80% of a good paint job is preparation. Expect to pay 30% upfront, 70% on completion."},
        {"question": "When is the best time to paint exterior in Kansas?", "answer": "Ideal exterior painting conditions are 50-85°F with low humidity and no rain in the forecast. In Johnson County, late spring through early fall (May-September) works best. Avoid painting in direct summer sun (causes blistering) or when temperatures drop below 50°F (paint won't cure properly). If painting in summer, start on the north side and work around the house following the shade."},
        {"question": "How long does exterior paint last in Kansas?", "answer": "Premium exterior paint on properly prepped surfaces lasts 8-15 years in Kansas. South and west-facing walls fade faster due to UV exposure. Wood siding needs repainting every 6-10 years, fiber cement every 10-15 years, and stucco every 10-15 years. Kansas weather extremes (hail, ice, heat, wind) reduce paint life. Watch for peeling, cracking, or fading as signs it's time to repaint."},
        {"question": "Should I paint or replace my kitchen cabinets?", "answer": "Paint if your cabinets are solid wood, in good structural condition, and you like the layout. Painting costs $3,000-$8,000 vs $15,000-$40,000+ for replacement. Cabinet painting requires special enamel paint and extensive prep (degreasing, sanding, priming). Hire a pro for the best results — DIY cabinet painting often looks amateur after 6 months. The ROI on professional cabinet painting is one of the highest home improvements."},
        {"question": "What paint finish should I use for each room?", "answer": "Flat/matte for ceilings and low-traffic walls (hides imperfections). Eggshell for living rooms, bedrooms, and hallways (slight sheen, washable). Satin for kitchens, bathrooms, and kids' rooms (more washable, resists moisture). Semi-gloss for trim, doors, and cabinets (durable, easy to clean). High-gloss for doors and furniture (maximum durability). In Kansas humidity, use at least eggshell in bathrooms with shower."},
    ],
    "garage-door": [
        {"question": "How much does garage door repair cost in Johnson County?", "answer": "Common repairs: spring replacement $150-$350, cable repair $100-$200, roller replacement $100-$250, opener repair $150-$300, and sensor alignment $75-$150. Full garage door replacement runs $700-$2,500 for a single door and $1,200-$4,000 for a double, installed. Premium insulated doors with windows can reach $3,000-$5,000+. Most companies offer free estimates."},
        {"question": "Why won't my garage door open or close?", "answer": "Most common causes: broken torsion spring (door feels very heavy), misaligned safety sensors (LED lights blink on motor), stripped gear in opener, broken cables, or track misalignment. First check: are the sensor lights solid (not blinking)? Is the motor humming but door not moving (stripped gear)? Does the door feel heavy when pulled manually? Never attempt to repair torsion springs yourself — they're under extreme tension and can cause serious injury."},
        {"question": "How long do garage door springs last?", "answer": "Torsion springs last 10,000-20,000 cycles (7-15 years for typical use of 2-4 cycles/day). Extension springs last 5,000-10,000 cycles. Signs of wear: visible gaps between coils, rust, squeaking, or the door dropping quickly when opened. Always replace springs in pairs — if one breaks, the other is near end-of-life. Professional spring replacement is $150-$350 and takes about an hour."},
        {"question": "Should I repair or replace my garage door?", "answer": "Replace if: the door is over 15-20 years old, multiple panels are damaged, you want better insulation (R-value 10+ saves on energy), or you're updating your home's exterior. Repair if: the door is under 10 years old, only one panel is damaged (replacement panels are available), or it's a simple mechanical issue (springs, cables, rollers). A new insulated door can reduce garage temperature by 10-15°F in summer."},
        {"question": "What garage door brands are best for Kansas weather?", "answer": "Look for doors with good insulation (polyurethane core, R-value 12+) and weatherstripping. Top brands available locally include Clopay, Amarr, Wayne Dalton, and CHI Overhead Doors. For Kansas extremes, choose insulated steel or fiberglass — wood doors require more maintenance and can warp in humidity swings. Wind-load rated doors are recommended if your HOA or city requires them."},
        {"question": "Can I install a garage door opener myself?", "answer": "DIY installation is possible for belt or chain-drive openers ($150-$400 for the unit) if you have basic electrical and mechanical skills. Plan 4-6 hours for a first install. However, torsion spring work should ALWAYS be left to professionals — springs store enough energy to cause serious injury or death. Most local companies charge $250-$500 for professional opener installation including haul-away of the old unit."},
    ],
    "tree-service": [
        {"question": "How much does tree removal cost in Johnson County?", "answer": "Tree removal in Johnson County ranges from $400-$1,500 for small trees (under 30ft), $800-$2,500 for medium trees (30-60ft), and $1,500-$5,000+ for large trees (60ft+). Factors affecting price: tree size, species (hardwoods cost more), proximity to structures, and whether the stump is included. Stump grinding adds $100-$400. Emergency removal after storm damage runs 2-3x normal rates."},
        {"question": "When should I trim my trees?", "answer": "Most deciduous trees are best pruned during dormancy (late fall through early spring, November-February in Kansas). This reduces disease transmission and stress. Dead or hazardous branches can be removed anytime. Spring-flowering trees (redbud, dogwood) should be pruned right after they bloom. Avoid pruning oaks April-October to prevent oak wilt. For mature trees, hire an ISA certified arborist."},
        {"question": "Do I need a permit to remove a tree in Johnson County?", "answer": "Most Johnson County cities require a tree removal permit for trees over a certain diameter (typically 6-12 inches at breast height). Overland Park, Olathe, and Lenexa all have tree preservation ordinances. Removing a tree without a permit can result in fines of $500-$2,500+ and replacement requirements. Your tree service should handle permits. Dead, diseased, or hazardous trees may be exempt — check with your city."},
        {"question": "How do I know if my tree is diseased or dying?", "answer": "Warning signs: significant dead wood in the crown (more than 25% is serious), mushrooms or fungal growth at the base, bark peeling or cracking, leaves turning color early or dropping prematurely, visible rot or cavities, and leaning with exposed roots. Emerald ash borer has devastated Kansas ash trees — if you have ash trees, have them inspected annually. Early treatment with trunk injections can save infested trees."},
        {"question": "What should I look for in a tree service company?", "answer": "Essential: ISA certified arborist on staff, general liability insurance ($1M+), workers compensation insurance, and proper equipment (bucket truck, crane for large jobs). Ask for proof of insurance and call to verify — uninsured tree work is extremely dangerous. Get 3+ written estimates. Beware of door-to-door solicitors offering tree work, especially after storms. Never pay in full upfront."},
        {"question": "Is stump grinding necessary?", "answer": "Stump grinding is recommended if: the stump is in a visible or trafficked area, you plan to landscape or build nearby, or it's a tripping hazard. Stumps also attract termites and other pests. Grinding costs $100-$400 per stump depending on size. Chemical stump removal takes 6-12 months and isn't always effective. Leaving the stump in place is fine in wooded areas but can sprout new growth from the root system."},
    ],
    "windows": [
        {"question": "How much does window replacement cost in Johnson County?", "answer": "Window replacement in Johnson County runs $300-$800 per window installed for standard double-hung vinyl windows, $500-$1,200 for fiberglass, and $800-$2,000+ for wood-clad. A typical home (15-20 windows) costs $5,000-$20,000 total. Energy-efficient options with Low-E glass and argon gas add 10-20% but can reduce energy bills by 12-33%. Most companies offer free in-home estimates."},
        {"question": "How long do replacement windows last?", "answer": "Vinyl windows: 20-40 years, fiberglass: 30-50 years, wood-clad: 20-30 years (with maintenance). Kansas weather (temperature swings, UV, storms) reduces lifespan. Signs you need replacement: drafts, condensation between panas, difficulty opening/closing, rotting wood, and rising energy bills. Quality windows from established brands (Andersen, Marvin, Pella, Simonton) outlast budget brands significantly."},
        {"question": "Should I replace all windows at once or a few at a time?", "answer": "Replacing all at once is typically 10-20% cheaper per window because installation labor is more efficient. It also ensures consistent appearance and lets you negotiate volume discounts. However, if budget is tight, prioritize: 1) windows with broken seals (foggy glass), 2) south/west-facing windows (most heat gain), 3) windows in main living areas. Some companies offer financing with 0% interest for 12-24 months."},
        {"question": "What window features matter most for Kansas climate?", "answer": "For Kansas extremes: double-pane Low-E glass (reduces heat transfer by 40-70%), argon gas fill (better insulation than air), vinyl or fiberglass frames (won't rot like wood), and a U-factor of 0.30 or lower. For south/west windows, consider triple-pane or Low-E 366 glass for maximum solar heat reduction. Impact-resistant glass is worth it if you're in a hail-prone area — it can prevent costly replacement after storms."},
        {"question": "How do I choose a window replacement company?", "answer": "Get 3+ quotes. Key questions: What brand and model exactly? What's the warranty (glass, frame, labor)? Is installation included? Do they handle permits? Are they the manufacturer or a dealer? Avoid companies that pressure same-day decisions or won't let you keep the quote. Look for 50+ Google reviews with 4.5+ stars. The best windows poorly installed perform worse than average windows properly installed."},
        {"question": "Can I replace windows myself?", "answer": "DIY window installation is possible for experienced homeowners with construction skills, but risks include: improper flashing (causes water damage), air leaks (defeats energy efficiency), voided warranties (most manufacturers require professional installation), and code violations. Labor is typically 30-50% of the total cost. For most homeowners, the warranty protection and proper installation justify hiring a pro."},
    ],
    "pest-control": [
        {"question": "How much does pest control cost in Johnson County?", "answer": "One-time treatment runs $150-$400 depending on pest type and home size. Quarterly service plans cost $50-$100 per visit ($200-$400/year) and include prevention for common pests. Termite treatment is $500-$2,500+ depending on severity. Bed bug treatment runs $500-$2,000. Most companies offer free inspections and will match or beat competitor pricing."},
        {"question": "What pests are most common in Johnson County?", "answer": "Top concerns: termites (subterranean, active March-November), ants (odorous house ants and carpenter ants), spiders (brown recluse and wolf spiders), roaches (German and Oriental), mosquitoes (May-October), mice and voles (fall/winter intruders), and wasps/yellowjackets. Kansas also has increasing issues with emerald ash borer (trees) and ticks carrying Lyme disease."},
        {"question": "How often should I have pest control service?", "answer": "Quarterly (every 3 months) is standard for most homes in Johnson County. This covers seasonal pest cycles: spring ants and termites, summer mosquitoes and wasps, fall spiders and mice seeking warmth, and winter rodent control. Bi-monthly works for homes with fewer pest pressures. Monthly service is only needed for severe infestations. Most companies offer free re-treatment between scheduled visits if pests return."},
        {"question": "Is pest control safe for pets and children?", "answer": "Modern professional pest control uses EPA-registered products applied at concentrations that target insects while being safe for mammals. Most require staying off treated surfaces for 1-4 hours until dry. Inform your technician about pets, children, and any sensitivities. They can use botanical or low-toxicity alternatives (borates, diatomaceous earth, essential oil blends) for interior treatment if preferred."},
        {"question": "How do I know if I have termites?", "answer": "Signs: mud tubes on exterior walls or foundation, discarded wings near windows/doors (spring swarmers), hollow-sounding wood when tapped, soft spots in flooring, and tiny holes in drywall with frass (termite droppings). Kansas subterranean termites are active and can cause $3,000-$10,000 in damage before detection. Get a professional inspection — most companies offer free termite inspections. If buying a home, always require a termite clearance letter."},
        {"question": "Can I handle pest control myself?", "answer": "DIY products (baits, sprays, traps) work for minor issues like a few ants or one mouse. They fail for: termites (need professional barrier treatment), bed bugs (resistant to consumer products and spread quickly), significant roach infestations, and carpenter ants (nest in structural wood). Store-bought chemicals are often less effective, applied incorrectly, and can make problems worse by causing pests to spread to new areas."},
    ],
    "auto-repair": [
        {"question": "How much does auto repair cost in Johnson County?", "answer": "Shop labor rates in Johnson County range from $100-$160/hour. Common services: oil change $40-$80, brake pads $150-$350 per axle, battery replacement $150-$300, alternator replacement $400-$800, and timing belt $500-$1,000. Dealerships charge 20-40% more than independent shops. Always get a written estimate before approving work, and don't be afraid to get a second opinion on repairs over $500."},
        {"question": "How do I find a trustworthy mechanic?", "answer": "Look for: ASE certification, 4.5+ star Google reviews (50+ reviews), shops that explain problems clearly and show you the worn parts, written estimates before work begins, and warranties on parts and labor (12 months/12,000 miles minimum). Ask neighbors and coworkers for recommendations. Avoid shops that pressure you into immediate repairs or can't explain why a service is needed."},
        {"question": "Should I go to a dealer or independent shop?", "answer": "Dealerships are best for: warranty work, recall repairs, and complex brand-specific issues. They have factory-trained technicians and access to the latest technical bulletins. Independent shops are better for: routine maintenance, older vehicles out of warranty, and most repairs. They charge 20-40% less and often provide more personalized service. For basic services (oil changes, brakes, batteries), an independent shop saves money with equal quality."},
        {"question": "What regular maintenance does my car need?", "answer": "Follow your owner's manual (not the dealer's upsell list). Standard schedule: oil change every 5,000-7,500 miles (synthetic), tire rotation every 5,000-7,500 miles, brake inspection every 20,000 miles, coolant flush every 30,000-50,000 miles, transmission fluid every 30,000-60,000 miles, and timing belt every 60,000-100,000 miles. Kansas extreme temperatures stress batteries — have yours tested every fall after 3 years."},
        {"question": "What are signs my car needs immediate attention?", "answer": "Don't ignore: check engine light (especially if flashing = serious), grinding or squealing brakes, pulling to one side when braking, engine temperature gauge in the red, smoke from exhaust or under hood, fluid leaks (red=transmission, green/orange=coolant, brown=oil, clear=brake fluid), unusual vibrations at speed, and difficulty starting. A flashing check engine light means pull over safely and call a tow — driving can cause catastrophic damage."},
        {"question": "Can I use aftermarket parts instead of OEM?", "answer": "Aftermarket parts can save 20-60% versus OEM and are fine for most repairs. Quality varies — ask for tier-1 brands (Bosch, Denso, Monroe, etc.). Use OEM for: safety-critical components (airbags, brake rotors in some cases), hybrid/EV battery systems, and complex electronic modules. For routine items (filters, brake pads, belts, sensors), quality aftermarket is perfectly acceptable and often made by the same suppliers as OEM."},
    ],
    "dentist": [
        {"question": "How much does dental work cost in Johnson County?", "answer": "Common procedures: routine cleaning and exam $100-$250, filling $150-$400, crown $800-$1,800, root canal $700-$1,500, teeth whitening $300-$600, and implants $3,000-$5,000 per tooth. Most dental insurance covers preventive care at 100% and basic procedures at 80%. Many Johnson County practices offer in-house discount plans ($200-$400/year) for uninsured patients that reduce procedure costs 20-40%."},
        {"question": "How do I choose a dentist in Johnson County?", "answer": "Consider: location and hours (evening/weekend availability), insurance participation, years of experience, technology (digital X-rays, same-day crowns), and patient reviews. Ask about their approach to treatment planning — good dentists present options at different price points. Visit the office before committing. Red flags: pushing expensive cosmetic work on your first visit, refusal to show X-rays, or pressure to finance large treatment plans."},
        {"question": "How often should I visit the dentist?", "answer": "The ADA recommends every 6 months for most people. You may need visits every 3-4 months if you have: gum disease, history of cavities, diabetes, or a weakened immune system. Even with good home care, professional cleanings remove tartar that brushing can't. Skipping regular visits turns $150 prevention into $1,500+ procedures. Most dental insurance covers 2 cleanings and exams per year at 100%."},
        {"question": "What's the difference between a dentist and orthodontist?", "answer": "All orthodontists are dentists, but only about 3% of dentists are orthodontists. Orthodontists complete 2-3 additional years of specialized training in tooth movement and jaw alignment. See a dentist for: cleanings, fillings, crowns, and root canals. See an orthodontist for: braces, clear aligners (Invisalign), bite correction, and jaw alignment issues. Some general dentists offer Invisalign but may have less experience with complex cases."},
        {"question": "Does dental insurance cover cosmetic procedures?", "answer": "Generally no — insurance covers medically necessary procedures. Covered: exams, cleanings, X-rays, fillings, root canals, and extractions. Not covered: teeth whitening, veneers, cosmetic bonding, and smile makeovers. Partially covered: crowns and bridges (50-80% if not purely cosmetic), orthodontics (many plans have a $1,500-$2,000 lifetime max for braces). Some practices offer financing (CareCredit, in-house plans) for cosmetic work."},
        {"question": "What should I do in a dental emergency?", "answer": "Knocked-out tooth: rinse gently (don't scrub), try to reinsert or keep in milk/saliva, and see a dentist within 30 minutes. Broken tooth: save pieces, rinse mouth, apply cold compress, and see a dentist same day. Toothache: rinse with warm salt water, floss to remove trapped food, take ibuprofen (not aspirin on gums), and call a dentist. Most Johnson County dental practices reserve same-day emergency slots — call first thing in the morning."},
    ],
    "movers": [
        {"question": "How much do movers cost in Johnson County?", "answer": "Local moves within Johnson County run $80-$150/hour for 2-3 movers with a 2-4 hour minimum. A typical 3-bedroom home move costs $600-$2,000. Long-distance moves are priced by weight and distance ($2,000-$8,000+). Extra charges: stairs ($50-$100 per flight), long carries ($50-$100), piano or safe moves ($150-$400 each), and packing services ($25-$50 per box packed). Get at least 3 in-home estimates."},
        {"question": "How far in advance should I book movers?", "answer": "Book 4-8 weeks ahead for moves during peak season (May-September, especially month-end). You can book 1-2 weeks ahead for off-season moves (October-April). Weekends and summer months fill up fastest. Last-minute bookings (less than a week) often carry a premium of 15-30%. Military families with PCS orders should ask about DOD-certified mover discounts."},
        {"question": "What should I look for in a moving company?", "answer": "Verify: USDOT number for interstate moves (search at fmcsa.dot.gov), Kansas intrastate authority for local moves, general liability and cargo insurance, and physical local address (not just a P.O. box). Get written estimates (not phone-only). Binding estimates guarantee your total cost; non-binding estimates can increase by up to 10%. Never pay a large deposit upfront — reputable movers collect on delivery."},
        {"question": "How can I save money on my move?", "answer": "Move mid-week and mid-month (cheaper than weekends/month-end). Declutter before moving — donate or sell items you don't need. Pack yourself (saves $500-$1,500). Use free boxes from local stores or Buy Nothing groups. Disassemble furniture yourself. Move small/fragile items in your own car. Get quotes from at least 3 companies. Some movers offer 5-10% discounts for military, seniors, or AAA members."},
        {"question": "What do movers not move?", "answer": "Most movers won't transport: hazardous materials (paint, chemicals, propane tanks), perishable food, plants (state regulations), pets, valuables (jewelry, cash, important documents — carry these yourself), and open containers of liquid. Ask your mover for their specific non-allowable list. Plan to transport these items yourself. For houseplants, check Kansas and destination state regulations if moving out of state."},
        {"question": "Should I get moving insurance?", "answer": "Yes. Basic carrier liability (released value) covers only $0.60 per pound per article — a $500 TV that weighs 30 lbs gets just $18. Full value protection covers replacement cost but costs 1-3% of declared value. For a $50,000 household shipment, expect to pay $500-$1,500 for full protection. Check your homeowner's or renter's insurance — some policies cover items in transit. Third-party moving insurance (from companies like MovingInsurance.com) offers another option."},
    ],
    "cleaning": [
        {"question": "How much does house cleaning cost in Johnson County?", "answer": "Standard cleaning runs $100-$200 per visit for a 2,000 sq ft home. Deep cleaning costs $200-$500. Move-in/move-out cleaning runs $250-$600. Recurring service (weekly/bi-weekly) costs less per visit ($80-$150) than one-time service. Most companies charge by square footage ($0.10-$0.20/sq ft) or by the hour ($30-$60/hour per cleaner). Many offer free in-home estimates for accuracy."},
        {"question": "How often should I have my house cleaned?", "answer": "Weekly service is ideal for families with kids or pets. Bi-weekly works well for most households. Monthly is fine for minimal-traffic homes. One-time deep cleaning is recommended seasonally or before events. A good cleaning service will customize a plan — not every room needs the same frequency. Kitchens and bathrooms benefit from weekly attention while guest rooms can go bi-weekly or monthly."},
        {"question": "What's included in a standard house cleaning?", "answer": "Standard service typically includes: vacuuming/mopping all floors, dusting surfaces and baseboards, kitchen counters and appliance exteriors, bathroom sinks/tub/toilet cleaning, mirror cleaning, trash removal, and bed making. Deep cleaning adds: inside appliances, cabinet/door wipe-down, light fixture cleaning, window sills, and baseboard scrubbing. Always confirm what's included before booking — services vary between companies."},
        {"question": "Should I hire an independent cleaner or a cleaning company?", "answer": "Independent cleaners ($20-$40/hour) are cheaper and often more consistent (same person every visit). But you handle scheduling, supplies, and taxes (if paying over $2,700/year, you may be required to issue a 1099). Cleaning companies ($40-$70/hour) provide insurance, background-checked employees, backup cleaners if yours is unavailable, and guaranteed satisfaction. For peace of mind and convenience, companies are worth the premium."},
        {"question": "Do I need to provide cleaning supplies?", "answer": "Most cleaning companies bring all supplies and equipment — this should be confirmed at booking. Some eco-friendly companies use only green products. If you prefer specific products (for allergies, pets, or fragrance sensitivity), most services will use what you provide. Independent cleaners vary — some bring supplies, some expect you to provide them. Always clarify before the first visit."},
        {"question": "What should I do before the cleaners arrive?", "answer": "Pick up clutter (clothes, toys, dishes) so cleaners can focus on actual cleaning rather than tidying. Secure pets in a safe area or let the service know if your pet is reactive. Leave notes for special instructions (delicate surfaces, rooms to skip). Provide parking instructions if needed. Most services prefer you're not home during cleaning — it's faster and more comfortable for everyone."},
    ],
    "pool": [
        {"question": "How much does pool service cost in Johnson County?", "answer": "Weekly pool maintenance runs $80-$150 per visit for standard service. Opening/closing services cost $200-$400 each. Acid washing runs $500-$1,000. Green pool cleanup (restoring a neglected pool) costs $300-$800. Full-service weekly plans include chemicals, brushing, vacuuming, and filter cleaning. Chemical-only plans cost $50-$80/week but require you to handle skimming and vacuuming yourself."},
        {"question": "How often should I have my pool serviced?", "answer": "Weekly service during swim season (May-September) is standard in Kansas. Bi-weekly works for pools with automatic covers and low usage. Monthly is only viable for closed pools or indoor facilities. During peak summer heat, chlorine depletes faster and algae grows quicker — skipping a week can turn a clear pool green in 2-3 days. Most companies offer seasonal packages that include opening, weekly maintenance, and closing."},
        {"question": "What does weekly pool service include?", "answer": "Standard weekly service includes: testing and balancing water chemistry (chlorine, pH, alkalinity, stabilizer), skimming debris, brushing walls and steps, vacuuming (manual or robot), emptying skimmer and pump baskets, checking filter pressure, and adding chemicals as needed. Some companies also check equipment operation (pump, heater, timer) and report any issues. Verify exactly what's included — some charge extra for filter cleaning and chemical shocks."},
        {"question": "Can I maintain my pool myself?", "answer": "Yes, but expect to spend 2-4 hours per week on maintenance. You'll need: test kit ($25-$50), chemicals ($50-$100/month), skimmer net, brush, vacuum, and basic knowledge of water chemistry. Common DIY mistakes: over-chlorinating, ignoring pH/alkalinity balance, running the pump too few hours, and not cleaning the filter regularly. A professional weekly visit costs about the same as your time value if you earn $40+/hour."},
        {"question": "When should I open and close my pool in Kansas?", "answer": "Opening: mid-April to early May, when nighttime temperatures consistently stay above 50°F. Closing: mid-September to early October, before first freeze. Opening earlier reduces algae growth (which explodes in warm stagnant water). Closing later gives you more swim time but risks freeze damage if a sudden cold snap hits. Professional opening/closing services include equipment inspection, cover removal/installation, and chemical balancing — $200-$400 each."},
        {"question": "How do I know if my pool has a leak?", "answer": "Signs: water level dropping more than 1/4 inch per day (normal evaporation), air bubbles in the return lines, soggy spots around the pool deck, constantly running autofill, and higher-than-normal water bills. The bucket test: fill a bucket with pool water, set it on the steps, mark water levels inside and outside the bucket, and check after 24 hours. If the pool level drops more than the bucket, you have a leak. Professional leak detection costs $200-$500."},
    ],
    "handyman": [
        {"question": "How much does a handyman cost in Johnson County?", "answer": "Handymen in Johnson County charge $60-$125 per hour, with a minimum service call of $75-$150. Common jobs: TV mounting $100-$200, faucet replacement $150-$300, drywall repair $150-$400, door installation $200-$500, and deck repair $300-$800. Many handymen offer half-day (4-hour) packages for $250-$400 and full-day (8-hour) packages for $450-$700. Get a quote before work begins — hourly rates can make small jobs expensive."},
        {"question": "What can a handyman do vs. what requires a licensed contractor?", "answer": "Handymen can handle: minor carpentry, painting, drywall patching, fixture installation, door/window repair, deck maintenance, and general home repairs. They CANNOT legally do: electrical work (beyond replacing a fixture), plumbing that modifies supply lines, structural changes, HVAC repair, or any work requiring a permit. For these, hire licensed electricians, plumbers, or contractors. Using a handyman for permitted work voids insurance coverage and can create liability when selling."},
        {"question": "Should I hire a handyman or a specialist?", "answer": "Hire a handyman for: a list of small jobs (saves multiple service calls), general repairs and maintenance, and projects under $1,000. Hire a specialist for: electrical, plumbing, HVAC, roofing, and any structural work. Specialists charge more per hour but complete work faster and correctly. A handyman plus painter plus plumber will cost more and take longer than a specialist for each trade. Rule of thumb: if it involves water, gas, or electricity beyond a simple swap, call a specialist."},
        {"question": "How do I find a reliable handyman in Johnson County?", "answer": "Best sources: neighborhood Facebook groups and Nextdoor (ask for recommendations), Angi (formerly Angie's List) for verified reviews, and Google reviews (look for 4.5+ stars with 20+ reviews). Verify insurance (general liability minimum). Ask about experience with your specific type of project. Get a written estimate. A good handyman is usually booked 1-3 weeks out — if they're available tomorrow, that may be a red flag."},
        {"question": "What should I have a handyman do in one visit?", "answer": "Maximize value by creating a prioritized list before they arrive. Good combo projects: drywall repair + paint touch-up, faucet replacement + caulk refresh, door repair + weatherstripping, deck board replacement + staining, and gutter cleaning + minor roof flashing repair. A skilled handyman can knock out 4-6 small tasks in a half-day visit. Grouping projects saves the minimum call fee and travel time charges."},
        {"question": "Is a handyman insured and what happens if something goes wrong?", "answer": "Reputable handymen carry general liability insurance ($500K-$1M) that covers property damage they cause. Ask for a certificate of insurance before work begins — a verbal claim isn't enough. If an uninsured handyman damages your property or is injured on your property, your homeowner's insurance may not cover it. Workers comp coverage is also important; without it, you could be liable for injuries. Never hire an uninsured handyman for projects involving water, electrical, or structural work."},
    ],
}

def api_request(method, path, data=None):
    url = f"{SUPABASE_URL}/rest/v1/{path}"
    headers = {
        "apikey": SERVICE_KEY,
        "Authorization": f"Bearer {SERVICE_KEY}",
        "Content-Type": "application/json",
        "Prefer": "return=minimal",
    }
    if data:
        req = urllib.request.Request(url, data=json.dumps(data).encode(), headers=headers)
    else:
        req = urllib.request.Request(url, headers=headers)
    req.method = method
    resp = urllib.request.urlopen(req)
    return resp

def main():
    # Fetch category IDs
    url = f"{SUPABASE_URL}/rest/v1/categories?select=id,slug,name"
    req = urllib.request.Request(url, headers={
        "apikey": SERVICE_KEY,
        "Authorization": f"Bearer {SERVICE_KEY}",
    })
    resp = urllib.request.urlopen(req)
    categories = {c["slug"]: c for c in json.loads(resp.read())}

    # Delete all existing FAQs
    print("🗑️  Deleting all existing FAQs...")
    api_request("DELETE", "faqs?id=neq.00000000-0000-0000-0000-000000000000")
    print("✅ Deleted all existing FAQs")

    # Insert city-agnostic FAQs
    total = 0
    for slug, faqs in CATEGORY_FAQS.items():
        cat = categories.get(slug)
        if not cat:
            print(f"  ⚠️  Category not found: {slug}")
            continue

        rows = []
        for faq in faqs:
            rows.append({
                "category_id": cat["id"],
                "city_id": None,
                "question": faq["question"],
                "answer": faq["answer"],
            })

        api_request("POST", "faqs", rows)
        print(f"  ✅ {len(rows)} FAQs for {cat['name']}")
        total += len(rows)

    print(f"\n✅ Total: {total} category-level FAQs uploaded")

if __name__ == "__main__":
    main()